### ISSUE TITLE
[Test] Basic Test for GMT should include a usage_scenario.yml file with a network

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#102]
Upgrade the current basic test which uses just a stress container to create two containers which are connected over a network.

This tests the network creating / deleting functionality of the tool in one go.

The containers do not have to communicate.

**Comment by dan-mm** [comment]
PR here: 
https://github.com/green-coding-berlin/green-metrics-tool/pull/133

tested this locally

**Comment by ArneTR** [comment]
I would like to have as an addition that you check if the network was actually created (docker network list ... or something like that)

**Comment by ArneTR** [comment]
please also remember to merge dev again in. The original branch-off from dev is probably outdated

**Comment by dan-mm** [comment]
It would be good to have this pr merged into dev first:
https://github.com/green-coding-berlin/green-metrics-tool/pull/128

As I re-wrote the basic tests to be split up in a better way, with a setup and individual tests for each check, and I'd like to add a network test on top of that work

**Comment by ArneTR** [comment]
FYI: I will put this on hold and up for discussion tomorrow. I do have questions regarding the branch setup.
