### ISSUE TITLE
Green Tests - Github Action

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#111]
Currently we are using custom code to run our tests only if a commit has happened in the last 24 hours.

It makes sense to offer this functionality as a global Github Action. The proposed name is "Green Testing Action".

It should encapsulate our current functionality in a reusable way that other Github Users just have to include our action and make minimal configuration:
- Which branch to run (by default the main branch of the repository the action is used on)
- What time interval to look for (by default 24 hours)
- ... more?

The integration should be minimal. Best way I currently can think of is a "uses" statement somewhere that tells the workflow to use our Github Action and a reference somwhere in a "needs" statement. Correct? Do we need more?

**Comment by dan-mm** [comment]
green-ci-branch-activity-checker
green-ci-carbon-aware
green-ci-energy
