### ISSUE TITLE
[GMT Test] Testing a usage_scenario.json file with ALL arguments and ALL command line switches (or permutation if they are exclusive)

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#114]
Please draft a testing concept HOW you plan to test for every of this switch and what the test should actually test for. Discuss on tuesday

Please also remember that this task should now check if the network was actually created (once the refactoring is done, which enablesto tests sub-parts of the run() function)

**Comment by dan-mm** [comment]
done - PR here: 
https://github.com/green-coding-berlin/green-metrics-tool/pull/154

branch name:
[usage-scenario-testing-114](https://github.com/green-coding-berlin/green-metrics-tool/tree/usage-scenario-testing-114)

example of a manual run in our CI:
https://github.com/green-coding-berlin/green-metrics-tool/actions/runs/4085083317

one test is WIP (name_is_in_db) as I'm not entirely sure yet how to properly test a the runner from the CLI in a sane way yet.
this test is meant to see if the --name passed shows up correctly in the DB. seems minor enough that skipping for now seems ok until we discuss in one of our tuesday meetings
