### ISSUE TITLE
Github summary of failing / passing tests in example applications and GMT

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#125]
============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.2.0, pluggy-1.0.0
rootdir: /home/runner/work/green-metrics-tool/green-metrics-tool/test
plugins: anyio-3.6.2
collected 3 items

api/test_api.py ..                                                       [ 66%]
tools/test_runner.py .                                                   [100%]

============================== 3 passed in 25.74s ==============================

=> This stuff to the Github Summary please

**Comment by dan-mm** [comment]
merged into dev and then into main:
https://github.com/green-coding-berlin/green-metrics-tool/pull/130
