### ISSUE TITLE
Checks in GMT Dashboard make domain agnostic

### ISSUE THREAD

**Issue by djesic** [green-coding-berlin/green-metrics-tool#126]
if (document.location.host.indexOf('metrics.green-coding.org') === 0)
        api_url = "https://api.green-coding.org";
    else
        api_url = "http://api.green-coding.local:8000";

Code shall be reworked to only detect if running on .local ... if so, then go to fixed api.green/coding.local/PORT BUT otherwise only change the subdomain

**Comment by ArneTR** [comment]
Please also note that the NGINX Server must listen on a different port. The config file are in the docker/nginx folder

**Comment by ArneTR** [comment]
the Pull Request link got lost: #131 

I have merged this already and will rather introduce a new ticket here later to make the framework really domain agnostic
