### ISSUE TITLE
Improvement: Output Summary

### ISSUE THREAD

**Issue by dan-mm** [green-coding-berlin/green-metrics-tool#138]
I had a look at the output summary of https://github.com/green-coding-berlin/example-applications/actions/runs/3944755155 and it is too garbled.

My improvement suggestion:
- Do not just write to file, but rather "tee" from the pytest output. This way it will land in a file and as well in the stdout of Github Actions
- grep everything between 
```
============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/runner/work/example-applications/example-applications/examples-directory/test
plugins: anyio-3.6.2
collected 12 items

smoke_test.py F.F...F.F... [100%]

=================================== .... ```

and display only that.

For details we still go to the logs ...

What do you think?

**Comment by dan-mm** [comment]
Fixed directly on dev here:
https://github.com/green-coding-berlin/green-metrics-tool/commit/4b46ed61dbd6c04a3a2420a15d0e7e8ebbd039a8

**Comment by ArneTR** [comment]
Looks good. Will open when it resurfaces
