### ISSUE TITLE
Invalid date null error in Actions

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#142]
https://github.com/green-coding-berlin/green-metrics-tool/actions/runs/4011206783/jobs/6888541599

`date: invalid date ‘null’`

**Comment by dan-mm** [comment]
fixed as part of #147 
https://github.com/green-coding-berlin/eco-ci-activity-checker/pull/1

Behaviour now:
If the api endpoint returns a null date for any reason, the action will no longer fail, and set should_run == true as we don't have any better information.
