### ISSUE TITLE
Tests show up as failed

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#147]
I have reworked the VM runs on Github actions to not spin up two VMs.

My main goal was to check if the run would still show as "failed" when actually the main testing part is skipped.

Sadly this is the case: https://github.com/green-coding-berlin/green-metrics-tool

For skipped runs we cannot show the failed status.

We need a rewrite of the eco-ci-activity-checker that it does not return a failure.

**Comment by dan-mm** [comment]
fixed and merged into eco-ci-activity-checker main branch.

PR for that merge here:
https://github.com/green-coding-berlin/eco-ci-activity-checker/pull/1

tested on personal fork here:
https://github.com/dan-mm/green-metrics-tool/actions/workflows/tests-vm-dev.yml
