### ISSUE TITLE
config.js

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#150]
1. rename current configuration.js to dashboard_settings.js
2. All domain calls should use a variable from the config.js file that is set throught install.sh script. the domain to b used is given in the config.yml file
3. config.js should be ignored in git
4. documentation has to be added
5. grep for any occurence of "green-coding"  to remove all domain mentions from the checked in code (apart from config.yml.example of course)

**Comment by djesic** [comment]
Fix typo in the name of configuration.html
