### ISSUE TITLE
Reorg Folders and Files

### ISSUE THREAD

**Issue by ribalba** [green-coding-berlin/green-metrics-tool#158]
- [ ] Sort the metrics_providers into macos, linux, misc 
- [ ] Move sdia and xboost under ac
- [ ] Move metrics_providers and runner.py into root
- [ ] Look into @djesic  tickets for tickets that correlate with this one 
- [ ] Powerspy needs to go into ac

**Comment by ribalba** [comment]
https://github.com/green-coding-berlin/green-metrics-tool/issues/85

**Comment by ArneTR** [comment]
I am currently working on this. Please do not start atm

**Comment by ArneTR** [comment]
Everything done apart from "Sort the metrics_providers into macos, linux, misc".

Documentation will be done by Danilo

**Comment by ArneTR** [comment]
I will also handle the keys in the usage_scenario.yml tomorrow
