### ISSUE TITLE
Fix setup-commands hack

### ISSUE THREAD

**Issue by ribalba** [green-coding-berlin/green-metrics-tool#159]
Currently in the user_scenario.yml you can get to server data through:
```
    setup-commands:
      - cp /etc/passwd /var/www/hacked
```
We need to make sure that only commands are executed that do not expose the underlying os

**Comment by ArneTR** [comment]
Do you have a working attack example? To my knowledge the command gets passed to the docker cli and this executes it in the container. No shell variable replacement is done beforehand or anything.

The example you give would copy the /etc/passwd from the docker container to a new location inside of the docker container
