### ISSUE TITLE
Badge in GMT repo that shows energy cost tests

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#161]
Open questions:
- Can we store the result from the energy estimator somewhere inside of Github?
- Can we read this information from a badge or through Github "blocks"
- https://blocks.githubnext.com/
  + Is maybe another feature from Github Blocks interesting for us? Short presentation for the team please!

If none of this will work. How can we make this through our GMT? New endpoint just for  CI runs?

**Comment by dan-mm** [comment]
Work done in the following 2 PR's:
https://github.com/green-coding-berlin/green-metrics-tool/pull/177
^^ This is the two new API endpoints, a new 'badges' table in the db, the migration, and a hacked together front-end that simply displays the badge (probably needs a bit more work on that front tbh)

https://github.com/green-coding-berlin/eco-ci-energy-estimation/pull/1
^^ this is the work for the Action itself, during the get-measurement task call it will additionally create and output the badge and a copy/paste version into the github summary

**Comment by dan-mm** [comment]
example of how it looks in the workflow here, btw:

https://github.com/dan-mm/green-metrics-tool/actions/runs/4223787984

**Comment by dan-mm** [comment]
More work needed:

- api endpoint needs to consume run_id
- api endpoint needs to make sure it returns the actual last (ORDER BY)
- front end needs to show a table with all Joule Values (no grouping yet)

**Comment by dan-mm** [comment]
More work needed:
- front end needs an info box with the static info regarding the CI run
- date formatting on value, and think about if any other columns are needed
- sql db should use value as int, and value_type for badges

**Comment by dan-mm** [comment]
PR's updated with all the latest code.

Make sure to merge in Danilo's graph work first 
https://github.com/green-coding-berlin/green-metrics-tool/pull/186
