### ISSUE TITLE
Jobs.py adapt to refactoring and actually test it! - It will also need the --config-override option

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#163]

**Comment by dan-mm** [comment]
work done in this PR:
https://github.com/green-coding-berlin/green-metrics-tool/pull/170

One of the tests (test_simple_email_job) is still a WIP - the patch to override the send_email function isn't working as I intended for some reason. I think I need to look at it with fresh eyes, but I didn't want to hold up the jobs.py not working for this one test, so I made the PR for this branch
