### ISSUE TITLE
Container Update Pipeline for our DockerHub Containers

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#166]
- Currently only the puppeteer container
- Should be a separate workflow

- Can we use a container registry on Github / Gitlab?
  + I see a blog article out of this with a back of the envelope calculation where we estiamte how much it would save to double-host our container on the girhub container registry and the gitlab container registry rather than only on docker hub.
  + Docker hub would be more flexible and reusable, but would mean that the network transfer would always have to happen and not stay internal to the CI-Tools-Datacenters

**Comment by dan-mm** [comment]
put it in GMT, find good folder name for it to live in (docker/auxilary-containers or something)

**Comment by dan-mm** [comment]
done in this PR:

https://github.com/green-coding-berlin/green-metrics-tool/pull/394

**Comment by ArneTR** [comment]
Closing this for overview purposes. Please everbody look in the PR for updates
