### ISSUE TITLE
Bugfix: copying of the badge in the metrics frontend does copy to much. Only <a> and <img> should be copied

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#176]

**Comment by djesic** [comment]
I noticed that this copy to clipboard functionality does not work on my local environment, `navigator.clipboard` is undefined.
https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined

I found a flag to switch to be able to work on this locally, but should we consider implementing some kind of fallback function to enable copying the badge when running on a local instance or is this use case not relevant?

**Comment by ArneTR** [comment]
jap, Dan hat the problem too. I have no good solution as a fallback. Do you have any?

**Comment by djesic** [comment]
I found this post: https://dev.to/ertanozdemir/copying-items-to-clipboard-without-using-clipboard-api-1a2o
It uses execCommand - https://caniuse.com/document-execcommand
However, it is deprecated but still available https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

**Comment by ArneTR** [comment]
Hmm, this feels like a soon to be broken functionality. I guess there is no real reason to copy the badge on local. I would suggest we rather make an alert box saying that copying on local is not working due to browser security models and thats it ...?
