### ISSUE TITLE
Usage Scenario for tests of Arrow

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#191]
https://github.com/green-coding-berlin/arrow

Please use https://gitlab.com/softawere-hackathon/test-arrow/-/blob/main/.gitlab-ci.yml as a helper to get the tests running. Or you find some documentation.

**Comment by djesic** [comment]
Attempt to move all commands from setup-commands into a shell script

**Comment by djesic** [comment]
Usage scenario changed to use provided script and dockerfile by the repo.
Called the runner by specifying the repo and branch https://github.com/green-coding-berlin/arrow/tree/usage-scenario
