### ISSUE TITLE
refactor the include mechanism in our files to an __init__ file

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#202]
TBD after the LCA rework of our tool!

Open Questions:
- Is __init__ still the way to go?
- How to handle our case where we include the base.py from the directory tree higher than the child classes?
- Everything in /lib should have prefixed imports with lib, so that the file knows it is in a subdirectory
- Also make lib. includes in the runner.py so we do not run into namespace issues. In general: Imports must have same syntactic structure throughout the repo

**Comment by ArneTR** [comment]
@saiteja13427 
Yes, very glad you are so active on our open issues and offer to contribute

The task is quite loosely specified. If in doubt please feel free to ping @djesic for detailed specifications

**Comment by saiteja13427** [comment]
My pleasure and thanks for the active support @ArneTR 
Sure, will reach out to him in case of any doubts!

**Comment by ArneTR** [comment]
This issue was stale and has actually been implemented in Sep 2023

https://github.com/green-coding-berlin/green-metrics-tool/pull/476

Thanks @saiteja13427 for offering support on this!
