### ISSUE TITLE
Eco-CI Energy Estimation rework

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#207]
- No measurement may be lost. Start-measurement should only append
- Every call to get-measurement should take an optional label. This should be display in the graphs
- get-measurement should only show the "lap" energy. Therefore two files need to be actually accumulating time. Only the one is resetted though every time get-measrument is called.
- show-total-and-badge

**Comment by dan-mm** [comment]
right now our front-end assumes all the ci info is coming from Github CI runs -> specifically the links to the repository/workflow assumes its github.

If we plan to support gitlab, or other CI pipelines, should we also have a "source" column in the  DB for values like github,gitlab, etc.?

this way the front end can create the correct links

**Comment by dan-mm** [comment]
repo - should be full HTTP url (as string)

**Comment by dan-mm** [comment]
note to self - update documentation!

**Comment by dan-mm** [comment]
This is done in two PR's
GMT Repo (database/api changes):
https://github.com/green-coding-berlin/green-metrics-tool/pull/226

Eco-Ci repo (main rewrite):
https://github.com/green-coding-berlin/green-metrics-tool/pull/226

Note:
I also made an additional change in how the eco-ci is used. As I was writing the documentation I realized it was a bit overly complicated from a user perspective, and could be simplified by having only 3 tasks - 'start-measurement' (which does that initialize used to + start the running cpu measurments), 'get-measurement' (for getting the lap measurements), and 'end-measurment' (for getting the total measurment + displaying badge).

**Comment by dan-mm** [comment]
more work:
- - rename End-Measurement to Final Measurement
- set flag for initalization, so if people call start-measurement twice by accident or misuse, bad won't happen
- remove dependency for having get-measrurment called at least once by having a flag set
