### ISSUE TITLE
Add a --fast parameter 

### ISSUE THREAD

**Issue by ribalba** [green-coding-berlin/green-metrics-tool#243]
When developing, especially `usage_sceario` files, a lot of time is spent waiting for sleeps and ideals that are needed when wanting to have correct runs but in most development cases they are not needed as the validity of the runs is not the main concern. I propose to introduce a `--fast` parameter that sets all the ideal times to 0 and loads a simple metrics provider. Currently I have to go into the config file disable everything and then enable again when pushing for a full test, which is often forgotten.

**Comment by saiteja13427** [comment]
@ArneTR I would like to take up this issue, can you throw some light on what exactly has to be done for this?

**Comment by ArneTR** [comment]
Hey @saiteja13427 .  I think this issue is stale.

@ribalba Can you confirm if this feature is still relevant?

**Comment by ArneTR** [comment]
We now have `--dev-no-sleeps`, `--dev-no-metrics` and `--dev-no-build` to speed the runs up.

Thanks @saiteja13427 for offering support on this one though!
