### ISSUE TITLE
[L] Refactor to new way we see runs

### ISSUE THREAD

**Issue by djesic** [green-coding-berlin/green-metrics-tool#255]
In the new GMT we have slightly changed the way we look at runs in relation to projects/ repos. It used to be that we have runs and they have a project. There was no concept of project having multiple runs. This has changed in the new codebase in which we look more at projects and then runs with various configurations. 

So please could you:
A new table `projects` should be created, which stores only the URIs of projects. The current table projects shall be renamed to `runs`. Then the `ci_measurements` and also the measurements of the GMT (`stats`) shall refer to the `runs` / `projects` table.
Please look at all the different parts of the backend and frontend that use the "old" terminology.

**Comment by djesic** [comment]
@ribalba This is what I came up with so far:

```sql
-- rename the projects table to runs
ALTER TABLE projects RENAME TO runs;

-- create a new projects table with ID and URI columns
CREATE TABLE projects (
  ID uuid PRIMARY KEY,
  URI VARCHAR(255)
);

-- add foreign keys to tables to reference the new projects table
ALTER TABLE ci_measurements
DROP CONSTRAINT IF EXISTS ci_measurements_projects_id_fkey,
ADD CONSTRAINT ci_measurements_projects_id_fkey FOREIGN KEY (project_id) REFERENCES projects (ID);

ALTER TABLE measurements
DROP CONSTRAINT IF EXISTS measurements_project_id_fkey,
ADD CONSTRAINT measurements_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE phase_stats
DROP CONSTRAINT IF EXISTS phase_stats_project_id_fkey,
ADD CONSTRAINT phase_stats_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE jobs
DROP CONSTRAINT IF EXISTS jobs_project_id_fkey,
ADD CONSTRAINT jobs_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (id);
```

**Comment by ArneTR** [comment]
Refactoring is now done in Release v0.19
