### ISSUE TITLE
Offer the option to change units to metric

### ISSUE THREAD

**Issue by ribalba** [green-coding-berlin/green-metrics-tool#258]
Currently it is gallons and miles I should be able to change it to km and litres.

**Comment by ArneTR** [comment]
We will never move away from imperial units! 🤡 

No, actually  a good idea.

A possible route of integration is setting a flag in the configuration page which will then be stored in the localStorage.

I would call it low prio and keep the issue open until we get the first +1 on this.

**Comment by shekhar-chauhan** [comment]
Could you please tell me where to add that change and then how would I be storing that in the localStorage ?? Would love to work on this !

**Comment by ArneTR** [comment]
Hi @shekhar-chauhan,

nice that you want to pick that up!

The [configuration.html](https://github.com/green-coding-berlin/green-metrics-tool/blob/main/frontend/configuration.html) is the site where all the configurations for the Dashboard display can be set.
There you would have to install a new toggle. Imperial units / metric units

The saving in the localStorage happens in the [dashboard_settings.js](https://github.com/green-coding-berlin/green-metrics-tool/blob/main/frontend/js/dashboard_settings.js) . You can derive the logic from there and just apply it to the new field.

The conversion factor  for km <-> miles and liters <-> gallons you have to pick up from the internet :)

The calculation for the CO2 boxes happens here:
- [Miles](https://github.com/green-coding-berlin/green-metrics-tool/blob/dev/frontend/js/stats.js#L605)
- [Gallons](https://github.com/green-coding-berlin/green-metrics-tool/blob/dev/frontend/js/stats.js#L606)

It would also be nice if you change the text on the box with javascript if imperial / metric units is selected.

Thank you again for your offer to pick it up!

**Comment by shekhar-chauhan** [comment]
hey @ArneTR, I have 0 knowledge in web dev. I'll try my best and let you know. Am I allowed to ask stupid questions?

**Comment by ArneTR** [comment]
It is a "good first issue", so it is expected that we provide some help.

Just try getting at it and ask if you get stuck. No fear of stupid questions :)
