### ISSUE TITLE
Rework `check_configuration` for PSU

### ISSUE THREAD

**Issue by djesic** [green-coding-berlin/green-metrics-tool#273]
The logic should rather check if a providers dot-notation contains ".energy." and ".machine$"

**Comment by ArneTR** [comment]
Also what I notices, what happens if no PSU provider is active. Should this fail? 

I would argue no, as every macOS provider then fails, which is very unintuitive.

**Comment by djesic** [comment]
Current logic checks if more than 1 is enabled. Zero is passing.
