### ISSUE TITLE
Display number of runs selected for comparison

### ISSUE THREAD

**Issue by djesic** [green-coding-berlin/green-metrics-tool#274]
Before clicking on the `Compare` button on `/index.html`, display the number of runs that are going to be compared.

Inside of `Project Data` on `/compare.html` display the number of compared runs

**Comment by saiteja13427** [comment]
@djesic This also looks doable to me, shall I take this up as well?

**Comment by djesic** [comment]
@saiteja13427 That would be lovely, thank you!
The compare functionality is only available on the `dev` branch at the moment.

Also, this was my proposal, I'd just like to get @ArneTR's go ahead on this before you start.

**Comment by ArneTR** [comment]
go :)

In order to properly test this you either have to duplicate some of the demo data or generate some runs on your machine.

Demo data contains only two projects.

If you cannot succeed duplicating demo data or running runs on your box ping me again and I will export some stuff from our live DB

**Comment by ArneTR** [comment]
I had a free slot and updated the demo data to now include 5 runs. This hopefully makes this task easier to tackle :)

**Comment by saiteja13427** [comment]
@djesic @ArneTR I am not able to properly work with the VM setup which I have done. On my PC, I am getting the following error when I run install script. 

Do you guys have any solution for it. Setup on my PC would speed up the development process by many times. Thus asking.

```
Building binaries ...
Installing ./metric_providers/lm_sensors/metric-provider-binary ...
make: Entering directory '/home/saiteja/opensource/green-metrics-tool/metric_providers/lm_sensors'
gcc source.c chips.c -o3 -Wall -Llib -lsensors -lglib-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -o metric-provider-binary
source.c: In function ‘main’:
source.c:326:17: warning: implicit declaration of function ‘g_string_replace’; did you mean ‘g_tree_replace’? [-Wimplicit-function-declaration]
  326 |                 g_string_replace(chip_feature_str, " ", "-", 0);
      |                 ^~~~~~~~~~~~~~~~
      |                 g_tree_replace
/usr/bin/ld: /tmp/cc0Vs2qj.o: in function `main':
source.c:(.text+0xbcc): undefined reference to `g_string_replace'
collect2: error: ld returned 1 exit status
make: *** [Makefile:8: binary] Error 1
make: Leaving directory '/home/saiteja/opensource/green-metrics-tool/metric_providers/lm_sensors'
```

**Comment by ArneTR** [comment]
What kind of VM are you using and what is your host operating system? If it is Windows you should also be able to run the tool in WSL 

This particular error I have so far only see on either a non-Ubuntu and non-Fedora distribution or Ubuntu < 22.04 , Which distribution did you use for the VM?

We sadly do not provide any development machines to test it with.

I have heard though that Github Codespaces should work. At least in a minimal setup where just one reporter is turned on (CPU procfs)

Let me know if any of these routes is available to you and where I shall explain in a bit more detail

**Comment by ArneTR** [comment]
@djesic Could you add  to https://docs.green-coding.berlin/docs/help/troubleshooting/ the error that @saiteja13427 was seeing. It comes from an outdated glib-2.0 package in Ubuntu < 22.04

**Comment by saiteja13427** [comment]
@djesic Yes, I tried this already, basically on ubuntu 20.04, it installs 2.64 only with this command, it doesn't install 2.68.

**Comment by ArneTR** [comment]
If you want an easy install routine Ubuntu 22.04 is mandatory.


I see three possible alternatives :
- commenting out the install routine in the https://github.com/green-coding-berlin/green-metrics-tool/blob/main/install_linux.sh#L73 Line 73-78
  + Then you cannot activate the `lm_sensors...` in the `config.yml` reporters, but the rest of the tool should work fine
- You can  install the newer `libglib` on your system alongside the official one from the package maintainer. I guess if you run Ubuntu as your daily driver you know how to do it.
- an OS upgrade to 22.04 with `sudo do-release-upgrade` as a last resort :)

**Comment by saiteja13427** [comment]
Oh yeah, thanks a lot @ArneTR 

I am going with first way. Now I have proper setup on my PC. Wit that contributing would be quite easy and fast. Thanks a lot for this. Will try to take up more issues and fix them!

**Comment by saiteja13427** [comment]
Added PR #295 for this issue

@djesic @ArneTR do review!
