### ISSUE TITLE
UI: Grouping of projects by URL

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#28]
On our overview page https://metrics.green-coding.org/ we currently list all measured projects.

The projects should be grouped by the URL. 

Currently we have multiple projects per URL and only the latest should show as a separate entry and the others should reveal on click.

A component from our CSS Framework should be used and adapted (https://fomantic-ui.com/)

**Comment by davidrui6** [comment]
Hey, I just watched the recording of your talk at the Bits & Bäume Conference and I really like the idea of this project.
I think I could help you out on this task. What do you think of an Accordion for the grouping of projects? [https://fomantic-ui.com/modules/accordion.html#tree](https://fomantic-ui.com/modules/accordion.html#tree)

**Comment by djesic** [comment]
Is now done on `dev` branch
