### ISSUE TITLE
[Ⓢ]  Eco-CI Add commit-hash, CPU, duration and display it all in the table

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#281]
And also add it to the workflows! I currently have only added it to dev by ingesting the testing branch from the eco-ci-energy-estimation

**Comment by ArneTR** [comment]
I already added commit-hash and CPU model, but it is in a branch. Please merge it to main

**Comment by dan-mm** [comment]
work for this is done in this branch:
https://github.com/green-coding-berlin/green-metrics-tool/tree/eco-ci-frontend-changes

I still need to add code to the eco-ci to calculate the duration per task though.

**Comment by ArneTR** [comment]
Done in v2.0
