### ISSUE TITLE
Lock dependencies in Dockerfile to specific versions [s]

### ISSUE THREAD

**Issue by djesic** [green-coding-berlin/green-metrics-tool#304]
https://github.com/green-coding-berlin/green-metrics-tool/blob/main/docker/Dockerfile-gunicorn#L8

Extract into a `requirements.txt` and lock versions

**Comment by ribalba** [comment]
You can also lock the versions on the command line if you want a quicker fix

**Comment by djesic** [comment]
That's what I did as a first pass with a `pip freeze` from a freshly build image.
I went ahead with a `requirements.txt` because I think dependabot might help us track versions here as well
