### ISSUE TITLE
Fixing versions for docker containers NGINX and Postgres

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#342]
At the moment we do not force any version for the docker containers in `/docker`

What I recently ran into is that I had to migrate the shared docker volume from our live server to an external mounted disk and also rebuilding the container.

`docker compose` does not auto update a container which is already present on the system.

Thus it can happen that PostgreSQL will stay in an older version (in our case it was 14.8). Atm [15.3 is the newest](https://hub.docker.com/_/postgres)
PostgreSQL will not accept the present database and forces to at least upgrade: https://www.postgresql.org/docs/current/pgupgrade.html

I propose we fix the postgres version in our docker files to a major version and add to the documentation that on updating the GMT also the DB might need to get updated if it shall be kept.

Any further additions? @ribalba

**Comment by ribalba** [comment]
Good catch. We should do that anyway as we should have the same system on the servers as we do in testing. 

We should also think about locking the packages like `lm-sensors` or at least check dependencies at some stage. Very low priority though IMHO.

**Comment by ArneTR** [comment]
This issue was stale. Versions have been fixed already in the v0.18 release and documentation to upgrade is here https://docs.green-coding.berlin/docs/installation/updating/#update-postgresql
