### ISSUE TITLE
GMT can exhaust hard disk space on cluster machines

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#348]
Currently we are experiencing that the hard disk space on the cluster machines gets exhausted after a while.

What I identified is that the docker client creates a lot of anonymous bind mounts that do never get cleaned. On the Blockheating box this is actually 83 GB in one week!

The command to fix it would be `docker volume prune`.

By definition it should only remove`anonymous local volumes not used by at least one container.` I think we should trigger this after every run, no matter if the `--full-docker-prune` flag is active or not.

What confuses me atm is that this is not the default behaviour of the docker client ... Why would I ever want to keep an anonymouse volume that I can never  access anyway as the container is gone?

@ribalba Maybe you have some more knowlege than I here? What happens if you do `docker volume prune` on your box for instance?

**Comment by ArneTR** [comment]
Here I added a link where this happened in the cluster. See the logs for details: https://metrics.green-coding.berlin/stats.html?id=829c05e8-7020-4cfe-8fcd-b701524a3875

**Comment by ribalba** [comment]
I think you could probably still access it if you specify it or is it maybe used by the layering system? I am not sure though.

I am not a big fan of deleting images we haven't created as this will actively delete data from a user. We can still use `--full-docker-prune` on our system. We can also add it to our warning message if disk space is getting low.

**Comment by ArneTR** [comment]
Thanks for pushing this.

Actually I have implemented a new flag, `--docker-prune` now, which will not force remove any images. However it will clear stopped containers. The flag is optional ... but recommended in docs and through a warning.

https://github.com/green-coding-berlin/green-metrics-tool/pull/401

Closing this as done.
