### ISSUE TITLE
Feature Request: Allow deleting runs

### ISSUE THREAD

**Issue by msts1906** [green-coding-berlin/green-metrics-tool#361]
It would be great it was possible to delete runs from the UI. Especially after a lot of debugging the runs accumulate and one can loose sight of the good runs.

**Comment by ribalba** [comment]
Hey @msts1906, thanks for raising this issue. This is something we have discussed repeatedly. The main thing is that we don't want to have logins and "secret" runs on our http://metrics.green-coding.berlin as we think every run has some validity. That is why we introduced the invalid flag for runs that have some sort of fault. For example all runs on MacOS are marked as invalid as the measurements are not reliable.

What one could do is save the "deleted" runs in a cookie in the browser but that is quite hacky and doesn't really solve the problem. What I could imagine though is that we make it easier on development machines to delete runs. You can do this manually now through SQL statements in the DB but it might be nice to have a delete button locally.

**Comment by ArneTR** [comment]
We now added the possiblity to delete in CLI mode: https://docs.green-coding.berlin/docs/measuring/deleting-measurements/

Does this help for your intended use case?

**Comment by msts1906** [comment]
Yes I was actually able to delete all failed runs. Thank you for the quick enhancement
