### ISSUE TITLE
Discuss if we really need a dev branch

### ISSUE THREAD

**Issue by ribalba** [green-coding-berlin/green-metrics-tool#41]
Currently the `dev` and `main` branch are quite far apart. I would like to discuss why we need a deb branch in the first place? What are the advantages of working with a dev branch and, if we need one, how can we ensure that features propagate to main in a timely manor.

**Comment by ArneTR** [comment]
Reason for the `dev` branch is to have a staging version that includes a feature that is ready to test by the community.

The other reason why we have this internally is that I want to merge features already into a common branch, that might not have the documentation written yet and thus should not necessarily show to the outside (which is the main branch)

Third reason is that we have a common branch that we can run tests against, which, if they succeed, prove that the code can be merged into main.

The reason why the branch is currently so far behind is that the feature of the DC-reporter which I am working currently is lacking documentation for the installation.

I will try to get this done by mid next week and then make a new release.
