### ISSUE TITLE
Fix sudo issue when using venv

### ISSUE THREAD

**Issue by ribalba** [green-coding-berlin/green-metrics-tool#438]
In the runner we use:
```
ps = subprocess.run(['sudo', sys.executable, python_file], stdout=subprocess.PIPE, check=True, encoding='UTF-8')
```
to call the hardware info script and we add an sudoers.d file `green_coding_hardware_info` with
```
ALL ALL=(ALL) NOPASSWD:/usr/bin/python3 /home/didi/code/green-metrics-tool/lib/hardware_info_root.py
```

when using a venv the python paths don't match anymore and we are asked to supply a password. Obviously this is not very nice. We somehow need a solution to include venvs here. 

Using a wildcard like
```
ALL ALL=(ALL) NOPASSWD:*/python3 /home/didi/code/green-metrics-tool/lib/hardware_info_root.py
```

is not an option as someone could crate a script and call it python3 and then run anything as root. 

I would suggest that we modify the install script to use venvs and then also modify the sudoers file.

**Comment by ArneTR** [comment]
is /usr/bin/env python3 an option?

**Comment by ribalba** [comment]
great idea :)
