### ISSUE TITLE
CI.JS - UX/UI Info Overhauls

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#446]
- Show name of the workflow and not the workflow ID in the eco-CI
- Number format in the ci stats table => 2.000.000.000,00 etc.
- Name of the workflow file somewhere in the eco-ci

**Comment by dan-mm** [comment]
Done in these two PR's: 

https://github.com/green-coding-berlin/green-metrics-tool/pull/467
https://github.com/green-coding-berlin/eco-ci-energy-estimation/pull/41

Also changed the ci-index page to condense all the projects by repo.
