### ISSUE TITLE
Refactor code to be clearer on container_id usage in providers

### ISSUE THREAD

**Issue by ribalba** [green-coding-berlin/green-metrics-tool#45]
Providers have the functionality to report data for multiple containers. So a metrics provider can output data as such:
```
time value container_id
```
This allows a provider to output data for multiple containers. 

We are also using this to output data for various other types thought. For example in `lm_sensors` we are misusing this functionality to output the feature values. While this works fine we should refactor the code to not use the `container` wording as this is quite confusing for people who don't know the code and our little "hack".

**Comment by ArneTR** [comment]
I pushed something to dev which renames the field container_name to detail_name throughout the whole codebase and DB.

In turn the RAPL reporters can now return two values or more. One for each package. The result looks then like here: https://metrics.green-coding.org/stats.html?id=311f35af-1c93-4150-bb45-9eda94582709 (look at the two graphs in the RAPL charts).

Is that fine for you in terms of understanding? Than I would update the documentation.

2. regarding the _fake_container ... I believe you mean that `-s` is added. correct? You should not  need this than anymore. as you just need to add the metric to the base.py and the provider.py ... I will take care of this in the merge though.
The line in the *CpuEnergyRaplMsrSystemProvider* would look like this:
`self._metrics = {"time":int, "value":int, "package_id":str}`

**Comment by ArneTR** [comment]
Stale. Implemented a while ago
