### ISSUE TITLE
System Checks error: No free memory

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#472]
I ran into the error 'No free memory! Please kill some programs' on my mac development machine while having no strong system activity.

The memory was indeed 70%+ used in the Activity Monitor, my question is though, should we treat this as a bad sign?

Is it not todays OS habit to use all the RAM available and purge applications only if need for memory exists? An OS having memory unused is rather untypical I feel nowadays ... but can really only speak for macOS.

@ribalba How is your Linux experience here?

**Comment by ribalba** [comment]
I think Mac and Linux are quite different here. Mac keeps stuff around as long as possible to speed up access times. Linux or Fedora doesn't do this as a aggressively. IMHO. 

I feel this check is more for server deployments where this would be a problem. If we would run into swapping the measurements would not be accurate anymore. 

I would refactor this once we do the splitting between development and server mode.

**Comment by ArneTR** [comment]
This is closed as the feature is now by default in the GMT system checks
