### ISSUE TITLE
How do we get the sustainable software tag?

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#535]
Like here https://github.com/topics/sustainable-software?l=python&o=desc&s=stars

Maybe also sustainability and #green?

**Comment by dan-mm** [comment]
It can be done easily, via a setting in the repo's main page (under about to the right side):
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

Need admin privileges on repo to do this though, so I can't add them.

I've taken a look through what some tags other people are using and compiled a list here, + how many repos use these tags:

climate-change - 1099 *
sustainability - 740 *
carbon-emissions - 208 
carbon-footprint - 203
energy-data - 181
metrics-gathering - 159
sustainable-development-goals - 126
co2-emissions - 99 *
sustainable-software -51 *
power-consumption - 37
green-software - 30 *
green-energy - 27 *
green-computing - 26
climate-change-mitigation - 17
power-consumption-measurement - 13
carbon-footprint-estimation - 6 
carbon-footprint-calculator - 5 *

Lets discuss tomorrow which ones we want to add (the ones marked with a * are my recommendations)

**Comment by ArneTR** [comment]
is there a downside of setting too many?

**Comment by ArneTR** [comment]
@ribalba Any further ideas?
