### ISSUE TITLE
Allow digits in environment variable keys

### ISSUE THREAD

**Issue by davidkopp** [green-coding-berlin/green-metrics-tool#540]
Currently, digits in keys of env vars as part of the compose file are not allowed. However, digits are quite common in Linux env vars and are allowed by the [Open Group Base Specification](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap08.html) (A.K.A. POSIX Regulation):

> Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in [Portable Character Set](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap06.html#tagtcjh_3) and do not begin with a digit.

**Comment by ArneTR** [comment]
Hey David,

thanks for the PR and providing the additional sources. We should adhere to the standard here.

Just triggered the test run in your PR and will merge ASAP.

Ty ❤️
