### ISSUE TITLE
Allow more characters in environment variable values

### ISSUE THREAD

**Issue by davidkopp** [green-coding-berlin/green-metrics-tool#569]
Currently, only values in the environment section of a compose file are allowed that match the regex `^[a-zA-Z0-9_]+[a-zA-Z0-9_-]*$`.

I have an application with a Docker Compose file that uses the following values:
- `http://backend:8080`
- `org.postgresql.Driver`
- `jdbc:postgresql://postgres/db`

These values are not allowed, because of the characters `:`, `/` and `.`
It is possible for me to change the application, so it doesn't need these environment variables anymore. Nevertheless, I want to ask if maybe some more characters could be allowed or the strict regex is required due to security concerns?

**Comment by ArneTR** [comment]
Thanks for question the regex here.

Having revisited this now for an hour with checking some source codes I would argue this is safe too loosen here.

We do not pass this ever to a shell command, as the env vars are only used in a plain list consuming `subprocess.run` command. This will always fork a process directly and host information or similar should be able to be captured there. Reference: https://github.com/python/cpython/blob/main/Lib/subprocess.py

When we really every use a `shell=True` we can still use `shlex.quote()`. - https://docs.python.org/3/library/shlex.html

@ribalba : Can you also give another opinion on this please?

**Comment by ArneTR** [comment]
I would maybe argue to still restrict the length to a sane amount to not run into any buffer / length issues. 256 characters for instance seems reasonable to me

**Comment by ribalba** [comment]
I think allowing `.`,`/` and `:` is not a problem. I would still not allow:
`*`, `?`, `|`, `;`, `<`, `>`, `$`, `{}`, `[]`, \`, `!`. If someone does ever manage to open a shell on the host system this could be an issue.

**Comment by ArneTR** [comment]
> I think allowing `.`,`/` and `:` is not a problem. I would still not allow: `*`, `?`, `|`, `;`, `<`, `>`, `$`, `{}`, `[]`, `, `!`. If someone does ever manage to open a shell on the host system this could be an issue.

@ribalba Can you give at my comment here: https://github.com/green-coding-berlin/green-metrics-tool/pull/577#issuecomment-1837069221
Would like to move discussion to PR
