### ISSUE TITLE
[TEST] In the GMT workflow it should be checked that all metric providers have actually successfully written data and in the DB there are rows for each

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#66]

**Comment by dan-mm** [comment]
done in this PR: 
https://github.com/green-coding-berlin/green-metrics-tool/pull/128

**Comment by ArneTR** [comment]
Upstreamed additional changes to https://github.com/green-coding-berlin/green-metrics-tool/pull/new/66-db-check-tests-improvements-arne

up for discussion tomorrow

**Comment by ArneTR** [comment]
The test_runner.py is currently broken for me:
````
psycopg2.OperationalError: connection to server at "green-coding-postgres-container" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
```
It seems like it is not picking up the correct test config file

**Comment by dan-mm** [comment]
This works for me when I try it locally, and as well as in our CI:
https://github.com/green-coding-berlin/green-metrics-tool/actions/runs/4094372476

I suspect this is a local error on your machine - perhaps we can take a look at it together tommorrow
