### ISSUE TITLE
Daily scheduling of Github actions in GMT (main/dev) currently broken

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#67]
We have seen test NOT running after 24h although there has been a commit in the last 24 hours.

**Comment by ArneTR** [comment]
It looks like this is the Run I should be looking at: https://github.com/green-coding-berlin/green-metrics-tool/actions/runs/3762157217

Both dev and main have been run, this is what I can see in the Jobs. The Run however says "main" only ... is this supposed to be this way?

- Should it actually have been two runs?
- Or should the Run be renamed to "main & dev"?

**Comment by ArneTR** [comment]
Update on this task:

- Please make dev and main runs as separate files in the workflow directory.

**Comment by dan-mm** [comment]
done: 
https://github.com/green-coding-berlin/green-metrics-tool/tree/tests-minor-cleanups/.github/workflows
