### ISSUE TITLE
When an entry in the GMT dashboard has no data the API completely aborts and nothing is shown. We would at least like to see the data from the projects table

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#68]
Sample: https://metrics.green-coding.org/stats.html?id=c3abc7e8-a68a-494c-8257-9c680d2548a7

Projects data in the top tabs could still be shown. Only charts etc. should empty on no data.

**Comment by djesic** [comment]
Project data lives in the `projects` table, but this data is obtained by the frontend by using the `GET /v1/stats/single/{id}` API call.
This API function calls an unexposed function `get_project` that gets this information and returns it as part of the `stats` response object.
The problem occurs when the `stats` table contains no measurements for this project, it returns a failure and doing so, it does not fetch any data about the project.

I am attempting to expose this `get_project` function on the API to make an independent call to it before getting notes and stats, and the API is returning 200 from the API docs and curl command, but failing when being called from the frontend.
Not finding the reason right now, could we please discuss this tomorrow?

I pushed my work here: https://github.com/green-coding-berlin/green-metrics-tool/tree/no_api_data_handling

**Comment by ArneTR** [comment]
Pull request has been merged in #75
