### ISSUE TITLE
Our tool must log the kernel it was running on via /proc/cmdline ... custom kernels might skew results

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#73]

**Comment by ribalba** [comment]
the /proc/cmdline doesn't actually specify the kernel as the name is just the filename which can just be kernel. A more reliable source is `/proc/version`. I decided to use `hostnamectl` because this also gives us loads of other data that might be interesting

**Comment by ArneTR** [comment]
Stale. Implemented a while ago
