### ISSUE TITLE
Code formatting and linting

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#82]
As discussed in the call today:
- Please integrate pylint or similar
- Please integrate black or similar
- Please integrate your C linting / formatting solution

NO need to lint all the branches. If you write a proper git pre-commit for us and a quick how-to to use these tools the branch maintainers should do that themselves.

Only liniting of main / dev would be nice to have from your side.

**Comment by djesic** [comment]
I recommend using `pyproject.toml` as the place to store Python tool configurations.

**Comment by ArneTR** [comment]
Stale. Implemented a while ago. We use pyling for now.

Switchting to ruff soon.
