### ISSUE TITLE
[SI] units matter - case sensitivity is important.

### ISSUE THREAD

**Issue by realvorl** [green-coding-berlin/green-metrics-tool#84]
Hello all, 

I just noticed a slight Frontend issue, that creates a big confusion:
![image](https://user-images.githubusercontent.com/6973263/208949476-c61259d3-10dd-4109-8f09-c6478f8ee87b.png)

You can see that server-side the value is correctly returned `16.24 mWh`   as in **milliwatt-hours**, but the UI simply uppercases that value, and we get **megawatt-HOURS** which is of course not correct. Other units like `grams (g) `get turned into the **`gravitational constant (G)`**

Love the tool, good work so far ! 
All the best !

**Comment by ArneTR** [comment]
Hey @realvorl, thanks for the input!

We are aware of this behaviour as it comes from the standard CSS Styling that we are using atm.

Since you now brought it again to our attention it makes sense to prioritze this confusion and I will update when we have this one fixed.

**Comment by ArneTR** [comment]
The update has been pushed to the `dev` branch. Please check if its now correct for you after clearing your caches. If not please reopen the pull request.
