### ISSUE TITLE
[Documentation] GMT file and naming restructuring

### ISSUE THREAD

**Issue by djesic** [green-coding-berlin/green-metrics-tool#85]
> Everything done as code. Just all needs to be documented. Let's phone for open questions.

-  Move the `runner.py` to the repository root for visibility and ease of use.
- move all metric providers from /tools/metric_providers to /metric_providers
- Rename the SDIA and XGBOOST reporters to include AC in their class name and directory structure -> Naming structure is Where, What, How, Scope
- Put this naming structure also in the docs that if somebody wants to contribute a provider this is the naming convention to follow
- Put the naming convetiong also in the docs in the overview file of the providers (https://docs.green-coding.org/docs/measuring/metric-providers/metric-providers-overview/)
- rename SDIA and XGBOOST provider in the docs 
- rename the powerspy2 provider to PsuEnergyAcSystemProvider and change paths and documentation accordingly. Old provider please just remove and make legacy in documentation

**Comment by ArneTR** [comment]
Everything done apart from the documentation. Please look at the current refactoring in Dev and rename paths / Names of classes accordingly
