### ISSUE TITLE
update readme.md badge

### ISSUE THREAD

**Issue by dan-mm** [green-coding-berlin/green-metrics-tool#87]
it should be looking at the schedualed VM workflow

**Comment by ArneTR** [comment]
I can see the badge at https://github.com/green-coding-berlin/green-metrics-tool/actions/runs/3762157217 but it gives me a convoluted picture of the `dev` and `main` branches combined.

I would like to have separate badges for dev and main.

The URLs that Github generates me for that are: 

[![Daily Test Run - Virtual Machine Main](https://github.com/green-coding-berlin/green-metrics-tool/actions/workflows/tests-vm.yml/badge.svg?branch=main)](https://github.com/green-coding-berlin/green-metrics-tool/actions/workflows/tests-vm.yml)
and
[![Daily Test Run - Virtual Machine Dev](https://github.com/green-coding-berlin/green-metrics-tool/actions/workflows/tests-vm.yml/badge.svg?branch=dev)](https://github.com/green-coding-berlin/green-metrics-tool/actions/workflows/tests-vm.yml)

To my understanding this will not work the way we have it set up. We would need to have separate Runs for separate branches as the "branch" variable never gets forwarded into the actual URL for the action?

Maybe this needs further discussion ... but the end-goal is separate badges

**Comment by dan-mm** [comment]
- the badges should link to the referenced run that has passed/failed/etc.

**Comment by dan-mm** [comment]
done and checked in on dev: https://github.com/green-coding-berlin/green-metrics-tool/blob/dev/README.md

- it links to the list of runs for the associated workflow - I couldn't find a way to link to the specific run without making an API call

- depending on when you read this, it might still show as broken: it will do so until the workflow is run for the first time, as its a new one

**Comment by ArneTR** [comment]
Unsure yet: How do they react to skips?

**Comment by ArneTR** [comment]
Confirmed: Skipped tests are shown as passing, which is what we want given we use the activity checker atm
