### ISSUE TITLE
Rework commits on branches used for Github Workflow development

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#90]
Currently in the `workflow-tweaks` branch the history is heavily polluted. 

Tryout: https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together 

Try compressing last 5 commits or so and then push -f everything to the branch

Please note that this is only to be used for branches that you work exclusively on. In order to see the changes from you I then have to delete my branch and reload it fresh. This is not suitable for shared branches like `main` or `dev`.

**Comment by ArneTR** [comment]
If you never switch the commit you are working on for trial and error this is my command:

`git add . && git commit --amend && git push -f``

If you however have already pushed commands this is what I do:

`git reset 473289478932 --soft && git add . && git commit -m "New try" && git push -f `

**Comment by dan-mm** [comment]
new branch history is cleaner:

https://github.com/green-coding-berlin/example-applications/commits/workflow-tweaks

**Comment by ArneTR** [comment]
Looks good!
